-- MySQL Script generated by MySQL Workbench
-- Sat May  7 11:13:34 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema diploma
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `diploma` ;

-- -----------------------------------------------------
-- Schema diploma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diploma` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `diploma` ;

-- -----------------------------------------------------
-- Table `diploma`.`analoggroups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`analoggroups` ;

CREATE TABLE IF NOT EXISTS `diploma`.`analoggroups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `analog_group_name` VARCHAR(150) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diploma`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`categories` ;

CREATE TABLE IF NOT EXISTS `diploma`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `category_parent_id` INT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `category_parent_id` (`category_parent_id` ASC) VISIBLE,
  CONSTRAINT `categories_ibfk_1`
    FOREIGN KEY (`category_parent_id`)
    REFERENCES `diploma`.`categories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 757
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diploma`.`details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`details` ;

CREATE TABLE IF NOT EXISTS `diploma`.`details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detail_category_id` INT NULL DEFAULT NULL,
  `detail_vendor_code` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `detail_name` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `detail_description` VARCHAR(150) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `detail_attributes` JSON NULL DEFAULT NULL,
  `detail_count` INT NULL DEFAULT NULL,
  `detail_cost` FLOAT NULL DEFAULT NULL,
  `analog_group_id` INT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `detail_category_id` (`detail_category_id` ASC) VISIBLE,
  INDEX `analog_group_id` (`analog_group_id` ASC) VISIBLE,
  CONSTRAINT `details_ibfk_1`
    FOREIGN KEY (`detail_category_id`)
    REFERENCES `diploma`.`categories` (`id`),
  CONSTRAINT `details_ibfk_2`
    FOREIGN KEY (`analog_group_id`)
    REFERENCES `diploma`.`analoggroups` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diploma`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`roles` ;

CREATE TABLE IF NOT EXISTS `diploma`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(150) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diploma`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`users` ;

CREATE TABLE IF NOT EXISTS `diploma`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_surname` VARCHAR(150) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `user_name` VARCHAR(150) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `user_lastname` VARCHAR(150) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `role_id` INT NULL DEFAULT NULL,
  `login` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `password` VARCHAR(150) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  `email` VARCHAR(150) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `role_id` (`role_id` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `diploma`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diploma`.`discounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`discounts` ;

CREATE TABLE IF NOT EXISTS `diploma`.`discounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `discount` FLOAT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `discounts_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `diploma`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diploma`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`orders` ;

CREATE TABLE IF NOT EXISTS `diploma`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `order_date` DATE NULL DEFAULT NULL,
  `order_cost` FLOAT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `diploma`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diploma`.`ordersdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`ordersdetails` ;

CREATE TABLE IF NOT EXISTS `diploma`.`ordersdetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detail_id` INT NULL DEFAULT NULL,
  `order_id` INT NULL DEFAULT NULL,
  `count` INT NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `detail_id` (`detail_id` ASC) VISIBLE,
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  CONSTRAINT `ordersdetails_ibfk_1`
    FOREIGN KEY (`detail_id`)
    REFERENCES `diploma`.`details` (`id`),
  CONSTRAINT `ordersdetails_ibfk_2`
    FOREIGN KEY (`order_id`)
    REFERENCES `diploma`.`orders` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `diploma`.`passwordresettokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diploma`.`passwordresettokens` ;

CREATE TABLE IF NOT EXISTS `diploma`.`passwordresettokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(150) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  `expiry_date` DATETIME NULL DEFAULT NULL,
  `created` DATETIME NULL DEFAULT NULL,
  `updated` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `PasswordResetTokens_users__fk` (`user_id` ASC) VISIBLE,
  CONSTRAINT `PasswordResetTokens_users__fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `diploma`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
